In [8]:
import pandas as pd
import numpy as np

start = pd.Timestamp.utcnow()
end = start + pd.DateOffset(minutes=5)
TOTAL_SAMPLES = 10000
t = pd.to_datetime(np.linspace(start.value, end.value, TOTAL_SAMPLES))

df = pd.DataFrame()
df['ts_start'] = t
df['ts_start'] = df.ts_start.astype('datetime64[s]')
df['ts_max'] = df.ts_start.apply(lambda x: x + pd.DateOffset(seconds=np.random.randint(10, 120)))
df['ts_end'] = df.ts_max.apply(lambda x: x + pd.DateOffset(seconds=np.random.randint(10, 120)))
df['frequency'] = df.ts_start.apply(lambda x: np.random.randint(800, 8000))
df['power'] = df.ts_start.apply(lambda x: np.random.randint(1, 10000))
df['latitude'] = 32.9002239196049
df['longitude'] = -96.96302798539023

df.tail()

,ts_start,ts_max,ts_end,frequency,power,latitude,longitude
9995,2021-10-13 23:41:54,2021-10-13 23:42:17,2021-10-13 23:43:42,2813,3895,32.900224,-96.963028
9996,2021-10-13 23:41:54,2021-10-13 23:42:55,2021-10-13 23:44:20,1849,5985,32.900224,-96.963028
9997,2021-10-13 23:41:54,2021-10-13 23:42:32,2021-10-13 23:44:18,5240,640,32.900224,-96.963028
9998,2021-10-13 23:41:54,2021-10-13 23:43:19,2021-10-13 23:45:11,4122,9545,32.900224,-96.963028
9999,2021-10-13 23:41:54,2021-10-13 23:42:11,2021-10-13 23:42:24,5793,5003,32.900224,-96.963028

In [9]:
df.to_parquet('sample-data.parquet', allow_truncated_timestamps=True)
df.to_csv('sample-data.csv')
df.to_csv('sample-data.csv.gz')